In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent = {
    'This is the first new sentence',
    'Here is the second new sentence',
    'A third sentence for the set',
    'Another one to add',
    'The fifth sentence goes here',
    'And the sixth one',
    'Finally, the seventh sentence'
}

In [7]:
sent

{'A third sentence for the set',
 'And the sixth one',
 'Another one to add',
 'Finally, the seventh sentence',
 'Here is the second new sentence',
 'The fifth sentence goes here',
 'This is the first new sentence'}

In [8]:
voc_size=1000

One Hot Representation


In [10]:
one_hot_rep = [one_hot(words, voc_size) for words in sent]
print(one_hot_rep)

[[221, 484, 96, 359], [654, 484, 903, 689], [809, 172, 359, 801, 484, 308], [791, 689, 321, 497], [115, 339, 484, 553, 441, 359], [484, 285, 359, 165, 115], [565, 339, 484, 34, 441, 359]]


In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [16]:
sent_lenght = 10
embedded_docs=pad_sequences(one_hot_rep, padding='pre', maxlen=sent_lenght)
print(embedded_docs)

[[  0   0   0   0   0   0 221 484  96 359]
 [  0   0   0   0   0   0 654 484 903 689]
 [  0   0   0   0 809 172 359 801 484 308]
 [  0   0   0   0   0   0 791 689 321 497]
 [  0   0   0   0 115 339 484 553 441 359]
 [  0   0   0   0   0 484 285 359 165 115]
 [  0   0   0   0 565 339 484  34 441 359]]


In [17]:
dim = 10


In [19]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_lenght))
model.compile('adam', 'mse')

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step
[[[ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
  [ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
  [ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
  [ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
  [ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
  [ 1.9917656e-02 -3.4135722e-02 -4.5678880e-02 -8.9082941e-03
   -3.3372641e-02  1.8016461e-02  3.3184614e-02 -1.7499734e-02
    2.0768467e-02 -1.4521290e-02]
 

In [23]:
embedded_docs[0]

array([  0,   0,   0,   0,   0,   0, 221, 484,  96, 359], dtype=int32)

In [24]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [ 0.01991766 -0.03413572 -0.04567888 -0.00890829 -0.03337264  0.01801646
   0.03318461 -0.01749973  0.02076847 -0.01452129]
 [-0.02181212  0.02351176 -0.04901152 -0.03405374 -0.0391958   0.00761814
   0.02003134 -0.01444105  0.01341816  0.03756049]
 [-0.02928708  0.0090868  -0.03647696 -0.02184575  0.03575989  0.01476452
  -0.03251181